services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WSRS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WSRS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WSRS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local #poderia ser qualquer coisa que armazenasse aquivos (Google Drive).
  pgadmin:
    driver: local #Se aplica o mesmo da frase acima.